### ISSUE TITLE
"duplicates" tab not showing in profile

### ISSUE THREAD

**Issue by DavidPostill** [Aran-Fey/SE-duplicate-manager#4]
Windows 7 Home Premium 64 bit, Firefox 92.0.1, ViolentMonkey 2.13.0, StackExchange duplicate manager 1.4

![Screenshot - 28_09_2021 , 21_39_35](https://user-images.githubusercontent.com/7079224/135162513-b8270a4e-b5d0-4662-96a1-517b5ef7cfdb.png)

**Comment by slear** [comment]
> Windows 7 Home Premium 64 bit, Firefox 92.0.1, ViolentMonkey 2.13.0, StackExchange duplicate manager 1.4
> 
> ![Screenshot - 28_09_2021 , 21_39_35](https://user-images.githubusercontent.com/7079224/135162513-b8270a4e-b5d0-4662-96a1-517b5ef7cfdb.png)

I confirm that this happens also on Edge in a Win10 box

**Comment by Aran-Fey** [comment]
Thanks for the report. There was a problem with the logic responsible for detecting whether you're currently viewing your own profile or someone else's. The issue should now be fixed; let me know if you still have problems.

**Comment by DavidPostill** [comment]
Thanks, it's visible now. I'll let you know if I come across any other
problems as I start to use it.
-- 
David Postill
