### ISSUE TITLE
Script not working: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by CherryDT** [Aran-Fey/SE-duplicate-manager#5]
I installed the script and opened an SO question and there was no new icon and instead I have the following error in the console:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at refresh_in_collection_status (userscript.html?name=StackExchange%2520duplicate%2520manager.user.js&id=7d495f25-2eda-46aa-a822-32c3b92896a1:1961:27)
```

I'm using latest Chrome with Tampermonkey.

**Comment by Aran-Fey** [comment]
Should be fixed now, as far as I can tell. I'm not active on SO anymore, but let me know if you find any other issues.
